applicationName: solr-frontend

workspace:
  size: 1Gi

pipelineRun:
  create: true
  sourceRepo: https://github.com/gattma/contest.git
  sourceRevision: 884a7b65ad052fdf49e771b39b520ee5b3666830 # eg.: 957ff8da4ce01a0908e26d67c806392b1e484c37
  imageRegistry: image-registry.openshift-image-registry.svc.cluster.local:5000
  imageRepository: # default = Release.Namespace
  builderImage: image-registry.openshift-image-registry.svc:5000/openshift/s2i-angular
  contextDir: solr/frontend/solr-search