apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.name }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  volumeMode: {{ .Values.storage.volumeMode }}
  storageClassName: {{ .Values.storage.storageClassName }}
