kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.deployment.name }}
    app.kubernetes.io/component: {{ .Values.deployment.name }}
    app.kubernetes.io/instance: {{ .Values.deployment.name }}
spec:
  ports:
    - name: 8983-tcp
      protocol: TCP
      port: 8983
      targetPort: 8983
  selector:
    deployment: {{ .Values.deployment.name }}
  type: ClusterIP
  sessionAffinity: None
