---
apiVersion: v2
name: solr-frontend-facade
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: gp-bke-deploy-quarkus
  version: 1.0.0
  repository: https://gepaplexx.github.io/gp-helm-charts/