apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-data-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: rook-ceph-fs
