applicationName: solr-frontend

workspace:
  size: 1Gi

pipelineRun:
  create: true
  sourceRepo: https://github.com/gattma/contest.git
  sourceRevision: 6a9e664d40499380afdb9c858774bfd15383c184 # eg.: 957ff8da4ce01a0908e26d67c806392b1e484c37
  imageRegistry: image-registry.openshift-image-registry.svc:5000
  imageRepository: # default = Release.Namespace
  builderImage: image-registry.openshift-image-registry.svc:5000/openshift/s2i-angular
  contextDir: solr/frontend/solr-search # eg.: frontend/management-ui