kind: Service
apiVersion: v1
metadata:
  name: openshift-solr
  namespace: contest
  labels:
    app: openshift-solr
    app.kubernetes.io/component: openshift-solr
    app.kubernetes.io/instance: openshift-solr
spec:
  ports:
    - name: 8983-tcp
      protocol: TCP
      port: 8983
      targetPort: 8983
  selector:
    deployment: openshift-solr
  type: ClusterIP
  sessionAffinity: None
